# Linux configuration
IF(UNIX AND NOT APPLE)
SET(CPLEX_ROOT_DIR "/opt/ibm/ILOG/CPLEX_Studio1210/cplex" CACHE PATH "CPLEX root directory")
FIND_PATH(CPLEX_INCLUDE_DIR 
	cplex.h
	PATHS "/opt/ibm/ILOG/CPLEX_Studio1210/cplex/include/ilcplex" 
	HINTS ${CPLEX_ROOT_DIR}/include)

FIND_LIBRARY(CPLEX_LIBRARY 
	libcplex.a
	PATHS "/opt/ibm/ILOG/CPLEX_Studio1210/cplex/lib/x86-64_linux/static_pic"
	HINTS ${CPLEX_ROOT_DIR}/lib/x86-64_linux/static_pic)

INCLUDE(FindPackageHandleStandardArgs)
# FIND_PACKAGE_HANDLE_STANDARD_ARGS(CPLEX 
# DEFAULT_MSG CPLEX_LIBRARY CPLEX_INCLUDE_DIR)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CPLEX
	FOUND_VAR CPLEX_FOUND
  	REQUIRED_VARS
    CPLEX_LIBRARY
	CPLEX_INCLUDE_DIR
	)

FIND_PATH(CPLEX_BIN_DIR
	cplex
	PATHS "/opt/ibm/ILOG/CPLEX_Studio1210/cplex/bin/x86-64_linux")

ENDIF()

# MacOS configuration
IF(APPLE)
SET(CPLEX_ROOT_DIR "" CACHE PATH "CPLEX root directory")

FIND_PATH(CPLEX_INCLUDE_DIR 
	cplex.h
	PATHS "/Applications/CPLEX_Studio1210/cplex/include/ilcplex" 
	HINTS ${CPLEX_ROOT_DIR}/include)

FIND_LIBRARY(CPLEX_LIBRARY 
	libcplex.a
	PATHS "/Applications/CPLEX_Studio1210/cplex/lib/x86-64_osx/static_pic"
	HINTS ${CPLEX_ROOT_DIR}/lib/x86−64_osx/static_pic)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CPLEX
	FOUND_VAR CPLEX_FOUND
  	REQUIRED_VARS
    	CPLEX_LIBRARY
		CPLEX_INCLUDE_DIR
	)

FIND_PATH(CPLEX_BIN_DIR
	cplex
	PATHS "/Applications/CPLEX_Studio1210/cplex/bin/x86−64_osx")

ENDIF()

IF (CPLEX_FOUND)
	SET(CPLEX_INCLUDE_DIRS ${CPLEX_INCLUDE_DIR}) 
	SET(CPLEX_LIBRARIES ${CPLEX_LIBRARY}) 
	IF(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        SET(CPLEX_LIBRARIES "${CPLEX_LIBRARIES};m;pthread;dl") 
  ENDIF(CMAKE_SYSTEM_NAME STREQUAL "Linux")
ENDIF (CPLEX_FOUND)

MARK_AS_ADVANCED(CPLEX_LIBRARY CPLEX_INCLUDE_DIR CPLEX_BIN_DIR)